---
version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=80
    volumes:
      - ./config:/config
      - ./watch:/watch
      - ./downloads:/downloads
      - ./data:/data
    ports:
      - 54042:54042
      - 54043:54043/udp
      - 80:80
    restart: unless-stopped
