name: Deploy

on:
  push:
    branches:
      - master

jobs:
  container:
    runs-on: ubuntu-bionic
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gay-eye-y" #Must be unique in Heroku
          heroku_email: "gayeye3184@hrandod.com"
          usedocker : true
          dontuseforce: true
          docker_heroku_process_type : worker
